### ISSUE TITLE
Proxying S3 files

### ISSUE THREAD

**Issue by twrichards** [guardian/actions-static-site#5]
@frederickobrien and I are considering moving to this approach for https://github.com/guardian/galaxies (which is primarily a static-site). At the moment however we use the 'server' module (node lambda, with aws-serverless-express and panda auth) to serve some additional data files from S3.

We're suggesting (and we're happy to have a go at the PR) having `[actions-static-site](https://github.com/guardian/actions-static-site)` take a new piece of config, something like...
```yaml 
proxyFromS3:
  bucket: "custom-app-data"
    "/api/a": "path/in/bucket.ext"
    "/api/b": "path/in/bucket.ext"
```

We would then proxy those files in the lambda (only if the user is authed).

https://aws.github.io/aws-sdk-go-v2/docs/getting-started/ looks fairly straight-forward.

We would want to support an optional `versionId` query param to forward on to https://ibm.github.io/ibm-cos-sdk-go/service/s3/GetObjectOutput.html#VersionId-field
